name: "Vprofile IAC"

on:
  push:
    branches:
      - main
      - stage
    paths:
      - '**/*.tf'  # This triggers for any Terraform file in any directory
      - terraform/**

  pull_request:
    branches:
      - main   # PR approval for main branch to be merged
      - stage 
    paths:
      - '**/*.tf'  # This triggers for any Terraform file in any directory  
      - terraform/**

env:
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  # S3 bucket for storing Terraform state
  BUCKET_TF_BUCKET: ${{ secrets.BUCKET_TF_BUCKET }}
  AWS_REGION: "us-east-1"
  EKS_CLUSTER_NAME: vprofile-eks

jobs:
  terraform:
    name: "Apply Terraform Code Changes"
    runs-on: ubuntu-latest  # Run the job on an Ubuntu environment
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4  # Checkout the source code

      - name: "Terraform Init"
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_BUCKET" -backend-config="region=$AWS_REGION"

      - name: "Terraform Format"
        id: format
        run: terraform fmt -check  # Check if the Terraform code is formatted correctly

      - name: "Terraform Validate"
        id: validate
        run: terraform validate  # Validate Terraform syntax

      - name: "Terraform Plan"
        id: plan
        run: terraform plan -no-color -input=false -out=planfile  # Create a plan file for consistency
        continue-on-error: true  # Allow this step to continue even if there are issues

      - name: "Terraform Plan Status"
        if: steps.plan.outcome == 'failure'
        run: exit 1  # Fail the workflow if Terraform plan fails
